# Generated by Django 5.0.10 on 2025-03-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business", models.CharField(max_length=255)),
                ("bus_phone", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=255)),
                ("cont_phone", models.CharField(max_length=20)),
            ],
        ),
    ]
