# Generated by Django 5.0.10 on 2025-03-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RentalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apt_number", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "tenant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tenant_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "bathrooms",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("penwell", "Penwell"),
                            ("airbnb", "Airbnb"),
                            ("commercial", "Commercial"),
                        ],
                        default="residential",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
