# Generated by Django 5.0.10 on 2025-03-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="bathrooms",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="city",
            field=models.CharField(default="Missoula", max_length=100),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="state",
            field=models.CharField(default="MT", max_length=100),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="street_address",
            field=models.CharField(default="107 South 3rd Street West", max_length=255),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="zip_code",
            field=models.CharField(default="59801", max_length=10),
        ),
    ]
