# Generated by Django 5.0.10 on 2025-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_alter_rentalproperty_bathrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="apt_number",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="city",
            field=models.CharField(default="Missoula", max_length=50),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="state",
            field=models.CharField(default="MT", max_length=10),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="street_address",
            field=models.CharField(default="107 South 3rd Street West", max_length=100),
        ),
    ]
