# Generated by Django 5.0.10 on 2025-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_alter_rentalproperty_apt_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="monthly_rent",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
