# Generated by Django 5.0.10 on 2025-03-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_alter_rentalproperty_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalproperty",
            name="apt_number",
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="monthly_rent",
            field=models.IntegerField(default=0),
        ),
    ]
