# Generated by Django 5.0.10 on 2025-03-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_alter_rentalproperty_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="apt_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="monthly_rent",
            field=models.IntegerField(default=0),
        ),
    ]
