# Generated by Django 5.0.10 on 2025-03-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "rentals",
            "0007_rentalproperty_name_alter_rentalproperty_apt_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentalproperty",
            old_name="apt_number",
            new_name="apt_num",
        ),
    ]
