# Generated by Django 5.0.10 on 2025-03-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0007_remove_rentalproperty_apt_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="monthly_rent",
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name="rentalproperty",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
