# Generated by Django 5.0.10 on 2025-03-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0008_rename_apt_number_rentalproperty_apt_num"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalproperty",
            name="apt_num",
        ),
        migrations.AddField(
            model_name="rentalproperty",
            name="apt_numb",
            field=models.IntegerField(default=0),
        ),
    ]
