# Generated by Django 5.0.10 on 2025-03-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0008_alter_rentalproperty_monthly_rent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="monthly_rent",
            field=models.IntegerField(default=0),
        ),
    ]
