# Generated by Django 5.0.10 on 2025-03-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_rentalproperty_apt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
