# Generated by Django 5.0.10 on 2025-03-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0011_rentalproperty_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentalproperty",
            name="apt_number",
        ),
    ]
