# Generated by Django 5.0.10 on 2025-03-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0012_remove_rentalproperty_apt_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalproperty",
            name="apt_numb",
            field=models.IntegerField(default=0),
        ),
    ]
