# Generated by Django 5.0.10 on 2025-03-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0013_rentalproperty_apt_numb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalproperty",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
