# Generated by Django 5.0.10 on 2025-03-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenance",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
